default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: aws_gauge_square
  password: yuya1016
  host: %

development:
  <<: *default
  database: myapp_database_development

test:
  <<: *default
  database: myapp_database_test

production:
  <<: *default
  database: myapp_database
